name: "Mark issues and pull requests as idle"
on:
  schedule:
    - cron: "49 11,23 * * *"

# See: https://github.com/actions/stale#recommended-permissions
permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  idle:
    uses: mdn/workflows/.github/workflows/idle.yml@main
    with:
      target-repo: "mdn/css-examples"
