name: "Lock old issues and pull requests"
on:
  schedule:
    - cron: "0 9 1 * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  lock:
    uses: mdn/workflows/.github/workflows/lock-closed.yml@main
    with:
      target-repo: "mdn/css-examples"
